---

- name: Copy krb5.conf into /etc
  copy: src=krb5.conf dest=/etc/krb5.conf
  sudo: yes
  tags: keytab

- name: Copy my keytab
  copy: src=keytab dest=~/keytab
  tags: keytab

- name: Check if keytab works
  command: kinit $USER@CRITEOIS.LAN -k -t ~/keytab
  tags: keytab

- name: Copy httpfs.sh script
  copy: src=httpfs.sh dest=~/httpfs.sh mode=750
  tags: backup

- name: Copy backup.sh script
  copy: src=backup.sh dest=~/backup.sh mode=750
  tags: backup

- name: Start Backup
  shell: ./backup.sh >logfile 2>&1 chdir=~
  tags: backup

- name: Clear snapshots
  shell: sudo nodetool clearsnapshot
  tags: clear

- name: Verify if snapshots are REALLY deleted
  shell: "[ $(find /var/opt/cassandra -type d |grep snap|wc -l) == 0 ]"
  tags: verify
